a = int(input("Enter value for a: "))
b = int(input("Enter value for b: "))
print("The value of ", a, "+", b, "=", a+b)
print("The value of ", a, "-", b, "=", a-b)
print("The value of ", a, "*", b, "=", a*b)
print("The value of ", a, "/", b, "=", a/b)
print("The value of ", a, "%", b, "=", a % b)
print("The value of ", a, "**", b, "=", a**b)
